name: CI

on:
  pull_request:
    branches: '*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build and run unittests
      run: |
        make test

    - name: Build and run integration tests
      run: |
        make integration-test
